version: '3.8'
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data/ 
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "${DB_USERNAME}"]
      interval: 5s
      timeout: 10s
      retries: 5

  api:
    build: ./api
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    volumes:
      - pdfs:/app/pdfs  
    depends_on:
      - db
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

  frontend:
    build: ./frontend
    ports:
      - 5001:5000
    volumes:
      - ./frontend:/app
    depends_on:
      - api

volumes:
  db-data:  
  pdfs:  