apiVersion: v1
kind: PersistentVolume
metadata:
  name: pdfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/pdfs"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdfs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi